Disable VSCode Black and isort extensions
Commit d75797d added support for the new Black and isort extensions for
Python in VSCode.

https://github.com/microsoft/vscode-black-formatter
https://github.com/microsoft/vscode-isort
https://open-vsx.org/extension/ms-python/black-formatter
https://open-vsx.org/extension/ms-python/isort

These could be helpful if they actually worked. They don't though.

When they were first installed, they errored out and never started up.

```text
Name: Black Formatter
Module: black
Python extension loading
[ERROR 2022-11-31 17:19:33.567]: Error initializing python: [
  TypeError: Cannot read properties of undefined
  (reading 'onDidChangeActiveEnvironmentPath')
	at t.initializePython (/Users/brendon/.vscode-oss/extensions/ms-python
  .black-formatter-2022.6.0-universal/dist/extension.js:1:4446)
	at runNextTicks (node:internal/process/task_queues:61:5)
	at process.processImmediate (node:internal/timers:437:9)
	at async Immediate.<anonymous> (/Users/brendon/.vscode-oss/extensions/
  ms-python.black-formatter-2022.6.0-universal/dist/extension.js:1:313026)
]
Python extension loaded
```

When a Python file is then saved:

```text
Formatting requested before server has started.
```

Same error with `isort` extension:

```text
Name: isort
Module: isort
Python extension loading
[ERROR 2022-11-31 17:19:33.568]: Error initializing python: [
  TypeError: Cannot read properties of undefined
  (reading 'onDidChangeActiveEnvironmentPath')
	at t.initializePython (/Users/brendon/.vscode-oss/extensions/ms-python
  .isort-2022.8.0-universal/dist/extension.js:1:3919)
	at async Immediate.<anonymous> (/Users/brendon/.vscode-oss/extensions/
  ms-python.isort-2022.8.0-universal/dist/extension.js:1:312748)
]
Python extension loaded
```

The errors may be occurring because the Python extension itself is still
`ms-python.python@2021.9.1246542782` (see 02033b8 for explanation), but
neither the Black extension nor the `isort` extension list a minimum
supported version of the `ms-python.python` extension.

This commit will partially revert the changes to settings.json added in
d75797d so that VSCode can actually format Python code again.