Revert "Add SoftRAID to Brewfile"
This reverts commit 7a96d5999bbd7ea0ae2cd22ace2b50f27bd74d43.

The SoftRAID version in Homebrew is out of date. Homebrew is on 6.3 but
the current version is SoftRAID 7.5. Even if version 6.3 were desired,
install fails with a `403 Unauthorized` error:

```text
Installing softraid
Error: Download failed on Cask 'softraid' with message:
Failure while executing;
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl \
  --disable \
  --cookie \
  /dev/null \
  --globoff \
  --show-error \
  --user-agent Homebrew/4.1.10\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.2\)\ \
  curl/8.1.2 \
  --header \
  Accept-Language:\ en \
  --retry 3 \
  --fail \
  --location \
  --silent \
  --head \
  --request GET \
  https://downloads.owc.com/softraid/mac/6/SoftRAID\%206.3.dmg
exited with 22. Here's the output:
curl: (22) The requested URL returned error: 403
HTTP/2 403
content-type: application/xml
date: Sun, 10 Sep 2023 02:08:45 GMT
server: AmazonS3
x-cache: Error from cloudfront
via: 1.1 0a72bb7be10458e1aefa37a097f21894.cloudfront.net (CloudFront)
x-amz-cf-pop: MIA3-C2
x-amz-cf-id: s1OGiF9KNMwy7KoKblR2Bom0BdeDCe40NNXLjV6BqG0ZXD1_08Uxrg==
vary: Origin
```