Remove Eleventy and Gridsome from npm globals
Gridsome is a cool project and I'll probably use it again in the future.

Eleventy (11ty) is billed as an alternative to Jekyll, like Jekyll with
npm packages instead of Ruby Gems. However, they don't provide migration
guides or tooling for migrating from Jekyll.
I tried migrating br3ndonland.github.io from Jekyll to Eleventy with:
https://24ways.org/2018/turn-jekyll-up-to-eleventy/
which I found in the 11ty docs: https://www.11ty.dev/docs/tutorials/

Once I got past the initial installation steps, I quickly realized it
was going to get complicated and time-consuming, and wouldn’t provide
substantial advantages over Jekyll for my small personal site. It would
be easier to just build a completely new website, which I plan to do,
probabably with Gridsome or Nuxt.

When spinning up the Eleventy site, the navigation was broken. The
homepage showed up, and I could get to the about page by manually typing
http://localhost:8080/about.html, but none of the nav links worked.

It was also unclear how to use JavaScript packages. Do I make them
plugins or something?_ For example, if I get rid of js/prism.js, or the
JavaScript imported from CDNs in my <script tags>, and use npm packages
instead, do I make them plugins in .eleventy.js? I tried this:

```js
module.exports = (eleventyConfig) => {
  const syntaxHighlight = require("prismjs")
  eleventyConfig.addPlugin(syntaxHighlight)
  return {
    dir: {
      layouts: "_layouts",
    },
  }
}
```

Error: The argument 'id' must be a non-empty string. Received ''