Revert "Switch from Docker Desktop to Podman"
This reverts commit 4a5c285be08d8b1d0b564063f100b454b89a9c86.

Docker Desktop 4.6 speed improvements should help.
https://www.docker.com/blog/speed-boost-achievement-unlocked-on-docker-desktop-4-6-for-mac/

I've had constant problems with Podman.
https://github.com/containers/podman/blob/main/troubleshooting.md

The Podman implementation of a Dockerfile is not in sync with the Docker
implementation of a Dockerfile. For example, with Podman, each `ARG` in
a Dockerfile has to be on its own line. Docker added the ability to have
multiple `ARG`s on a single line years ago.

Oftentimes, when I pull an image built with Docker, then try to run it
with Podman, it doesn't run. I have to build it with Podman directly.

During `podman machine start`, I get warnings and errors, including
`ERRO[0015] Couldn't restablish ssh tunnel on path` and
`WARN[0015] API socket failed ping test`, but then it also says
`Machine "podman-machine-default" started successfully`. What?

And then when trying to build:, it tells me:

```text
Cannot connect to Podman. Please verify your connection to the Linux
system using `podman system connection list`, or try
`podman machine init` and `podman machine start` to manage a new Linux VM

Error: unable to connect to Podman socket: server API version is too
old. Client "4.0.0" server "3.4.4"
```

Why are the podman client and server out of sync?
Why can't Podman connect to itself, when it "started successfully"?