Update to pnpm 12
- https://pnpm.io/blog/releases/12.0
- https://pnpm.io/blog/releases/12.4
- https://pnpm.io/blog/whats-different-in-pnpm-12
- https://github.com/pnpm/pnpm/releases

pnpm/pnpm#14527 (released in pnpm 12.4.1) introduces a shell fallback, but mise's embedded installer
skipped pnpm's build script and generated a launcher that fed that shell
script to Node.js. Adding `allow_builds = ["pnpm"]`` to the mise config
resolves the issue.

- https://mise.jdx.dev/dev-tools/backends/npm.html#lifecycle-scripts
- https://github.com/jdx/mise/discussions/12559
- https://github.com/pnpm/pnpm/pull/14527

```
.dotfiles on main [⇡]
❯ mise install
npm:pnpm@12.4.1   installing 2/2 pkgs                                          ✔

.dotfiles on main [⇡]
❯ pnpm --version
file:///Users/brendon/.local/share/mise/installs/npm-pnpm/12.4.1/node_modules/.mise/pnpm@12.4.1/node_modules/pnpm/pnpm:1
# pnpm's native binary replaces this file during installation (see
^

SyntaxError: Invalid or unexpected token
    at compileSourceTextModule (node:internal/modules/esm/utils:346:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:110:18)
    at #translate (node:internal/modules/esm/loader:559:20)
    at afterLoad (node:internal/modules/esm/loader:612:29)
    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:617:12)
    at #createModuleJob (node:internal/modules/esm/loader:640:36)
    at #getJobFromResolveResult (node:internal/modules/esm/loader:353:34)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:321:41)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:680:25)

Node.js v22.23.2

.dotfiles on main [⇡]
1 ❯
```